name: Stickii
version: 1.2
main: org.katastrophe.Stickii.Stickii
authors: [KieraanBreeze]
description: >
             Delete any block up to 50 blocks away with a stick.
commands:
  sticky:
    description: Bonk! Block go bye-bye!
    usage: |
            /stickii